version: '2'
services:
  nginx:
    image: nginx:1.10.1-alpine
    volumes:
    - ./src:/var/www
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
    - "8211:80"
    environment:
    - TZ=Europe/Moscow
  php:
    build: ./docker/php/build
    volumes:
    - ./src:/var/www
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    working_dir: /var/www/
    environment:
    - ICU_DATA=/opt/icu/