version: '2'
volumes:
  storage_files:
  cache_files:
services:
  nginx:
    extends:
      file: common-compose.yml
      service: nginx
    depends_on:
    - php
    volumes:
    - cache_files:/var/data/cache
  php:
    extends:
      file: common-compose.yml
      service: php
    volumes:
    - ./docker/php/dev/php.ini:/usr/local/etc/php/php.ini:ro
    - ./docker/php/dev/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    - storage_files:/var/data/storage