version: '2'
services:
  nginx:
    extends:
      file: common-compose.yml
      service: nginx
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        syslog-tag: "file-storage/nginx"
    depends_on:
    - php
    restart: always

  php:
    extends:
      file: common-compose.yml
      service: php
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        syslog-tag: "file-storage/php"
    restart: always
    volumes:
    - ./docker/php/prod/php.ini:/usr/local/etc/php/php.ini