#!/usr/bin/env bash

{
    source vendor/common.sh # For IDE
    . "${BASH_SOURCE%/*}/vendor/common.sh"
} 2>> /dev/null

section "Install composer dependencies"

case ${ENV} in
    ${ENV_DEV})
    docker exec ${CONTAINER_PHP} composer install
    ;;
    ${ENV_PROD})
    docker exec ${CONTAINER_PHP} composer install --prefer-dist --optimize-autoloader --no-dev
    ;;
esac